import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// If you want to automatically deploy the build output into your Obsidian vault,
// you can specify your vault's plugin directory here (or via an environment variable).
const vaultPluginPath = process.env.OBSIDIAN_VAULT_PLUGIN_PATH;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: 'copy-to-vault',
			setup(build) {
				build.onEnd(() => {
					if (vaultPluginPath && fs.existsSync(vaultPluginPath)) {
						try {
							fs.mkdirSync(vaultPluginPath, { recursive: true });
							fs.copyFileSync('main.js', path.join(vaultPluginPath, 'main.js'));
							fs.copyFileSync('manifest.json', path.join(vaultPluginPath, 'manifest.json'));
							if (fs.existsSync('styles.css')) {
								fs.copyFileSync('styles.css', path.join(vaultPluginPath, 'styles.css'));
							}
							console.log(`Successfully deployed plugin files to vault path: ${vaultPluginPath}`);
						} catch (err) {
							console.error(`Failed to copy build files to vault:`, err);
						}
					}
				});
			}
		}
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
